defaultPlatforms:
  - linux/arm64
  - linux/amd64

builds:
  - id: cert-manager-lego-webhook
    main: ./cmd/cert-manager-lego-webhook
    env:
      - CGO_ENABLED=0
    flags:
      - -v
    ldflags:
      - -s
      - -w
