apiVersion: v1
kind: Secret
metadata:
  name: alidns-secret
  namespace: cert-manager
type: Opaque
stringData:
  # Fill these in locally. Do not commit the completed file.
  # https://go-acme.github.io/lego/dns/alidns/#credentials
  ALICLOUD_ACCESS_KEY: ''
  ALICLOUD_SECRET_KEY: ''
