apiVersion: v2
name: cert-manager-lego-webhook
description: A cert-manager DNS-01 webhook supporting multiple DNS providers through lego.
type: application
version: 1.5.1
# The webhook version; chart-only releases can keep the same application image.
appVersion: "1.5.0"
home: https://github.com/yxwuxuanl/cert-manager-lego-webhook
sources:
  - https://github.com/yxwuxuanl/cert-manager-lego-webhook
keywords:
  - cert-manager
  - lego
  - dns-01
  - acme
  - tls
